# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())                           

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
A = np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
A = np.zeros((10,10))
print("%d bytes" % (A.size * A.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
print(np.info(np.add))
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
A = np.zeros(10)
A[4] = 1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
print(A[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
A = np.arange(9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
A = np.array([1,2,0,0,4,0])
print(np.where(A != 0))

A = np.nonzero([1,2,0,0,4,0])
print(A)

(array([0, 1, 4]),)
(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
A = np.array( [[1,0,0],
               [0,1,0],
               [0,0,1]] )
print(A)

A = np.eye(3)
print(A)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
A = np.random.random((3,3,3))
print(A)

[[[0.76943683 0.79531255 0.22200259]
  [0.21960132 0.59549643 0.63358315]
  [0.76637848 0.23269978 0.99028024]]

 [[0.68441335 0.47532334 0.67720338]
  [0.08450802 0.00273684 0.83333597]
  [0.0637306  0.6710675  0.4453618 ]]

 [[0.65082581 0.11402965 0.32976819]
  [0.39100683 0.63591748 0.86073861]
  [0.01424827 0.23765288 0.67969545]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
A = np.random.random((10,10))
print(A.min(), A.max())

0.0053383026150458646 0.9948760931529779


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
A = np.random.random((30))
print(A.mean())

0.5099068180236093


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
A = np.ones((10,10))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
A = np.ones((10,10))
A = np.pad(array=A, pad_width=1, mode='constant', constant_values=0)
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan,
np.nan == np.nan,
np.inf > np.nan,
np.nan - np.nan,
np.nan in set([np.nan]),
0.3 == 3 * 0.1)

nan False False nan True False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
A = np.diag(1+np.arange(4),k=-1)
print(A)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
A = np.zeros((8,8),dtype=int)
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
A = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
A = np.random.random((5,5))
A = (A - A.mean())/A.std()
print(A)

[[ 1.17635619 -0.80803782 -1.10617845 -1.41222704 -0.85707743]
 [-1.02150492  0.0713058  -0.82565534 -1.03770474 -0.70762834]
 [-0.37073783  1.67869211  0.92629779  0.21738265  1.42229172]
 [-1.22646984 -0.24665536  0.63140023  0.70282709 -0.83957164]
 [ 1.54207787  1.14043541  0.15620187 -0.75144027  1.54562028]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.arange(15).reshape((5, 3))
B = np.arange(6).reshape((3, 2))
AB = np.dot(A, B)
print(AB)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
A = np.arange(11)
A[(3 < A) & (A < 8)] *= -1
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.random.choice(10,4)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[        1        27        27 387420489]
[  1   4   4 256]
[False False False False]
[0.+1.j 0.+3.j 0.+3.j 0.+9.j]
[1. 3. 3. 9.]


ValueError: ignored

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
A = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(A)), A))

# More readable but less efficient
print(np.where(A>0, np.ceil(A), np.floor(A)))

[ 6. -6. -9.  8. -8.  3.  5.  6.  3. -3.]
[ 6. -6. -9.  8. -8.  3.  5.  6.  3. -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10)
print(np.intersect1d(A,B))

[2 3 4 5 6 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
A = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(A)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.random.random(5)
B = np.random.random(5)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-0.05262144, -0.07238159, -0.60362264, -0.46091436, -0.29016073])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
A = np.random.uniform(0,10,10)
print(A)
print(A.astype(int))
print(np.floor(A))
print(A - A%1) #%: 나누기 연산 후 나머지 구하기
print(A // 1) #//: 나누기 연산 후 소수점 이하의 수를 버리고, 정수 부분의 수만 구함

[4.9927246  4.65868096 6.46441273 5.31217286 4.61606698 5.05789878
 2.4772681  0.62990336 1.83280222 5.35114154]
[4 4 6 5 4 5 2 0 1 5]
[4. 4. 6. 5. 4. 5. 2. 0. 1. 5.]
[4. 4. 6. 5. 4. 5. 2. 0. 1. 5.]
[4. 4. 6. 5. 4. 5. 2. 0. 1. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
A = np.zeros((5,5))
A += np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    a = np.random.randint(0, 100, size=10)
    return a
A = generate()
print(A)

[45 76 73 60 96 49 42 68 74 47]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
A = np.random.random(10)
print(A)

[0.20182248 0.39262463 0.74266693 0.38673533 0.37729937 0.4086633
 0.79852817 0.90580027 0.65108028 0.03588967]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
A = np.random.random(10)
A = np.sort(A)
print(A)

[0.08610142 0.09180877 0.23156238 0.4404584  0.61199415 0.69918932
 0.71449156 0.716381   0.73416955 0.95406913]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
A = np.arange(10)
np.add.reduce(A) #reduce: 누적집계 내기 위함

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10)
print(A == B)
check_equal = np.array_equal(A,B)
print(check_equal)

[False False False False False False False False False False]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
A = np.zeros(10)
A.flags.writeable = False   #np.flags: 배열에 특정 속성에 대한 정보 명시
A[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)  #cartesian coordinates
T = np.arctan2(Y,X) #Converting to polar coordinates
print(R)
print(T)

[0.81265178 0.80147264 0.567949   0.46715255 0.33174383 0.52209012
 0.22849187 0.40503008 1.06644215 0.58147715]
[1.54713515 1.20769576 0.56911351 0.77343096 0.4697095  0.82631003
 0.88495994 0.42935926 0.8435537  0.74912301]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
A = np.random.random(10)
print(A)
A[np.argsort(A)[9]] = 0
print(A)

[0.69324157 0.22820115 0.87148832 0.91436075 0.5950527  0.68756634
 0.59878706 0.64763578 0.41209932 0.7945533 ]
[0.69324157 0.22820115 0.87148832 0.         0.5950527  0.68756634
 0.59878706 0.64763578 0.41209932 0.7945533 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
A = np.zeros((5,5), [('x',float),('y',float)])
A['x'], A['y'] = np.meshgrid(np.linspace(0,1,5),    #meshgrid: 격자 grid,
                             np.linspace(0,1,5))    #linspace: 1차원 배열 만들기
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(4)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429]
 [ 2.         -2.         -0.66666667 -0.4       ]
 [ 0.66666667  2.         -2.         -0.66666667]
 [ 0.4         0.66666667  2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
A = np.zeros((10,10))
np.set_printoptions(threshold=float("inf"))  #인쇄 옵션 설정
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

72


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
A = np.zeros(10,[ ('position',[ ('x',float,1),
                                ('y',float,1)] ),
                 ('color',    [ ('r',float,1),
                                ('g',float,1),
                                ('b',float,1)])] )
print(A)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
A = np.random.random((10,2))
X,Y = np.atleast_2d(A[:,0], A[:,1])
B = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(B)

[[0.         0.08400998 0.29468843 0.06963883 0.48082033 0.35926473
  0.66710845 0.29716477 0.36541094 0.70142302]
 [0.08400998 0.         0.23710702 0.13005315 0.40504817 0.4429611
  0.60274113 0.31394583 0.31064973 0.68221554]
 [0.29468843 0.23710702 0.         0.28458456 0.43911421 0.62407605
  0.67120678 0.54504699 0.07377204 0.86377165]
 [0.06963883 0.13005315 0.28458456 0.         0.5350891  0.3419704
  0.72981339 0.35965787 0.34927001 0.77032396]
 [0.48082033 0.40504817 0.43911421 0.5350891  0.         0.81419857
  0.23349927 0.47260729 0.47950912 0.53888748]
 [0.35926473 0.4429611  0.62407605 0.3419704  0.81419857 0.
  0.96127164 0.42818617 0.683923   0.84731233]
 [0.66710845 0.60274113 0.67120678 0.72981339 0.23349927 0.96127164
  0.         0.55855824 0.71300826 0.42198871]
 [0.29716477 0.31394583 0.54504699 0.35965787 0.47260729 0.42818617
  0.55855824 0.         0.61861167 0.43497197]
 [0.36541094 0.31064973 0.07377204 0.34927001 0.47950912 0.683923
  0.71300826 0.61861167 

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
A = (np.random.random(10)*100).astype(np.float32)
B = A.astype(np.int32)
print(B)

[37  1 41 42 79 37 28 37 53 48]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
A = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
B = np.genfromtxt(A, delimiter=",", dtype=np.int)   #데이터 읽기
print(B)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
A = np.random.randint(1,10,(3,3))
for index, value in np.ndenumerate(A):  #np.ndenumerate: 배열좌표와 값 쌍을 생성하는 반복자
    print(index, value)
for index in np.ndindex(A.shape):  #np.ndindex: 배열을 인덱스하기 위한 N차원 반복자
    print(index, A[index])

(0, 0) 8
(0, 1) 5
(0, 2) 8
(1, 0) 1
(1, 1) 7
(1, 2) 5
(2, 0) 8
(2, 1) 9
(2, 2) 4
(0, 0) 8
(0, 1) 5
(0, 2) 8
(1, 0) 1
(1, 1) 7
(1, 2) 5
(2, 0) 8
(2, 1) 9
(2, 2) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
A, B = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
D = np.sqrt(A*A + B*B)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
A = np.zeros((n,n))
B = np.random.choice(range(n*n),p,replace=False)
np.put(A, B, 1)
print(A)

[[0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
A = np.random.random((3,3))
B = A - A.mean(axis=1).reshape(-1,1)
print(B)

[[-0.06507905 -0.43032934  0.49540839]
 [-0.12766861 -0.18597727  0.31364589]
 [ 0.48263615 -0.01630407 -0.46633208]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
A = np.random.randint(0,10,(3,3))
print(A)
print(A[A[:,1].argsort()])

[[5 5 2]
 [3 3 0]
 [6 0 1]]
[[6 0 1]
 [3 3 0]
 [5 5 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
A = np.random.randint(0,2,(4,4))
print(A)
print(np.isnan(A).any())

[[0 0 1 0]
 [0 0 1 1]
 [0 0 0 1]
 [0 1 0 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
A = np.random.uniform(0,1,10)
x = 0.5
B = A.flat[np.abs(A - x).argmin()]
print(B)

0.45681636818953897


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.random.randint(0,10,(1,3))
B = np.random.randint(0,10,(3,1))
it = np.nditer([A,B,None])  #np.nditer: 하나 이상의 배열의 모든 요소에 접근
for x,y,z in it:
    z[...] = x + y
print(it.operands[2])

[[10 13 12]
 [ 5  8  7]
 [ 6  9  8]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

A = NamedArray(np.arange(10), "range_10")
print (A.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
A = np.ones(10)
I = np.random.randint(0,len(A),20)
A += np.bincount(I, minlength=len(A))
print(A)

[1. 4. 6. 2. 1. 3. 2. 3. 6. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = np.arange(5)
I = np.random.randint(0,len(X),len(X))
F = np.bincount(I,X)  #np.bincount: 9부터 최댓값까지 정렬 후 각각의 빈도수 반환
print(F)

[2. 0. 8. 0.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)